<?xml version="1.0"?>
<package format="3">
  <name>guidance_control</name>
  <version>0.1.0</version>
  <description>Guidance &amp; control (C++): waypoint follower, PID/pure pursuit</description>
  <maintainer email="tim@example.com">Tim Dagozilla</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>sensor_msgs</depend>
  <depend>geometry_msgs</depend>
  <depend>cv_bridge</depend>
  <depend>opencv2</depend>
  <depend>msgs</depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
